using System.Collections.Generic;
using StickFightColorCustomizer.Models;
using StickFightColorCustomizer.Hosting;

namespace StickFightColorCustomizer.Core
{
    public static class MenuLocalization
    {
        private static readonly Dictionary<string, string> English = new Dictionary<string, string>
        {
            { "tab_body", "Body" },
            { "tab_glow", "Glow" },
            { "glow_body_blend", "Body color blend" },
            { "body_gradients", "Bone gradients" },
            { "half_color", "Lower half color" },
            { "slot_add", "+ Add slot" },
            { "slot_rename", "Name" },
            { "tab_hats", "Hats" },
            { "tab_wingcust", "WINGCUST" },
            { "tab_shoes", "Shoes" },
            { "wing_hint", "Minigame wings — cosmetic only. Does not start the wing minigame." },
            { "wing_enable", "Enable wings" },
            { "wing_on", "Wings enabled." },
            { "wing_off", "Wings disabled." },
            { "wing_pick", "Enable the toggle to show wings in match." },
            { "wing_scale", "Wing size: " },
            { "wing_style", "Style: minigame (vanilla look)" },
            { "wing_not_ready", "NOT 100% FUNCTIONAL YET\nDO NOT USE" },
            { "wing_not_ready_hint", "Wings are disabled in-game until the next update. No CPU cost while off." },
            { "tab_weapons", "Weapons" },
            { "tab_slots", "Slots" },
            { "tab_advanced", "Advanced" },
            { "tab_settings", "Settings" },
            { "color_wheel", "Color wheel" },
            { "apply_now", "Apply now" },
            { "save", "Save" },
            { "load", "Load" },
            { "empty", "Empty" },
            { "saved", "Saved" },
            { "slot", "Slot" },
            { "style_presets", "Style presets" },
            { "weapon_presets", "Weapon presets" },
            { "weapon_neon", "Neon (glow)" },
            { "weapon_enable", "Enable weapon color" },
            { "body_enable", "Use custom body colors" },
            { "language", "Menu language" },
            { "english", "English" },
            { "spanish", "Spanish" },
            { "active", "Active" },
            { "save_config", "Save config (file)" },
            { "sync_lobby", "Sync lobby" },
            { "made_by_alka", "by alka · AlkaRealSkinChanger" },
            { "weapon_hint", "Equipped weapon only. Local view only." },
            { "slots_hint", "Save up to 3 style profiles." },
            { "menu_hint_keys", "F6 or Escape closes  |  T/Y close menu for chat" },
            { "body_part", "Body part" },
            { "body_enable_hint", "Enable the toggle to edit and apply body colors." },
            { "body_disabled", "Custom colors off (no per-frame cost)." },
            { "body_enabled", "Custom colors enabled." },
            { "repaint_body", "Repaint full body" },
            { "reset_part", "Reset part" },
            { "part_reset", "Part set to white." },
            { "body_applied", "Body applied." },
            { "halves_enable", "Enable half-color per bone" },
            { "halves_enable_hint", "Enable the toggle for gradients on spine, arms and legs." },
            { "halves_need_body", "Enable custom colors on the Body tab first." },
            { "halves_proximal", "proximal (from Body)" },
            { "halves_distal", "Distal (lower half)" },
            { "halves_bone_cut", "Bone cut: " },
            { "halves_apply", "Apply halves" },
            { "halves_applied", "Halves recalculated." },
            { "glow_color_label", "Aura color (independent from body)" },
            { "glow_enable", "Enable glow" },
            { "glow_on", "Glow enabled." },
            { "glow_off", "Glow disabled." },
            { "glow_updated", "Glow color updated." },
            { "glow_strength", "Strength: " },
            { "glow_zones", "Prefab zones" },
            { "glow_width", "Aura width: " },
            { "glow_alpha", "Transparency: " },
            { "glow_apply", "Apply glow" },
            { "glow_remove", "Remove glow" },
            { "glow_applied", "Aura applied." },
            { "glow_removed", "Glow removed." },
            { "zone_head", "Head" },
            { "zone_torso", "Torso" },
            { "zone_arms", "Arms" },
            { "zone_legs", "Legs" },
            { "zone_wings", "Wings" },
            { "hat_hint", "Local cosmetic + sync between mod players." },
            { "hat_enable", "Enable hat" },
            { "hat_on", "Hat enabled." },
            { "hat_off", "Hat disabled." },
            { "hat_pick", "Enable the toggle to pick a hat." },
            { "hat_model", "Model" },
            { "hat_classic", "Classic" },
            { "hat_categories", "Categories (10 each)" },
            { "hat_category_click_hint", "Click «10 OPTIONS» on a row to open the variant picker." },
            { "hat_variants_open", "10 OPTIONS ▶" },
            { "hat_variants_close", "◀ CLOSE" },
            { "hat_pick_variant", "pick one" },
            { "hat_close_panel", "Close" },
            { "shoe_hint", "Cosmetic only. No effect on gameplay." },
            { "shoe_enable", "Enable shoes" },
            { "shoe_on", "Shoes enabled." },
            { "shoe_off", "Shoes disabled." },
            { "shoe_pick", "Enable the toggle to pick shoes." },
            { "shoe_model", "Model" },
            { "shoe_coming_soon", "COMING SOON" },
            { "shoe_coming_soon_hint", "Shoe preview only — not applied in-game yet." },
            { "shoe_preview_label", "Preview (locked)" },
            { "tab_tops", "Tops" },
            { "tab_objects", "Objects" },
            { "objects_hint", "Orbiting / back cosmetics that follow your stickman." },
            { "objects_enable", "Enable objects" },
            { "objects_on", "Objects enabled." },
            { "objects_off", "Objects disabled." },
            { "objects_pick", "Enable the toggle to pick an object." },
            { "objects_scale", "Scale" },
            { "tops_hint", "Shirt cosmetic — profile view. Attaches to torso." },
            { "tops_enable", "Enable top" },
            { "tops_on", "Top enabled." },
            { "tops_off", "Top disabled." },
            { "tops_pick", "Enable the toggle to pick a top." },
            { "tops_model", "Model" },
            { "weapon_color", "Weapon color" },
            { "weapon_on", "Weapon color enabled." },
            { "weapon_off", "Weapon color disabled." },
            { "weapon_pick", "Enable the toggle to tint the equipped weapon." },
            { "weapon_updated", "Weapon color updated." },
            { "weapon_tint_mesh", "Tint mesh (lines / model)" },
            { "weapon_tint_particles", "Tint particles (muzzle, etc.)" },
            { "weapon_repainted", "Active weapon repainted." },
            { "options", "Options" },
            { "menu_size", "Menu window size" },
            { "menu_smaller", "Smaller −" },
            { "menu_larger", "Larger +" },
            { "menu_reset_size", "Reset size" },
            { "menu_size_hint", "Drag ◢ corner or use buttons. Saved in config." },
            { "mp_safe", "Vanilla-safe MP (recommended: no extra P2P packets)" },
            { "mp_safe_on", "Safe mode: vanilla compatible; sync between mods (Steam + ping)." },
            { "mod_sync_hint", "Players with the same DLL see each other's colors in lobby/match (Steam lobby + vanilla Ping). Hats sync via lobby." },
            { "mp_safe_off", "Advanced mode: no extra network restriction." },
            { "uniform_skin", "Unified skin (MP / simple mod look)" },
            { "rgb_anim", "Animated RGB (body only)" },
            { "glow_lobby", "Keep glow in lobby menu (off = more FPS)" },
            { "config_saved", "Config saved to disk." },
            { "sync_sent", "Sync sent." },
            { "skin_code", "Skin code (share)" },
            { "gen_code", "Generate code" },
            { "copy_code", "Copy code" },
            { "paste_import", "Paste code to import" },
            { "import", "Import" },
            { "paste", "Paste" },
            { "code_copied", "Code copied to clipboard." },
            { "code_pasted", "Code pasted." },
            { "code_invalid", "Invalid code. Must start with SFCCSKIN4|" },
            { "skin_imported", "Skin imported and applied." },
            { "code_fail", "Could not generate code." },
            { "code_ok", "Code generated. Use Copy code." },
            { "mp_sync_hint", "Mod sync: sfcc in lobby + ping in match. Vanilla players ignored." },
            { "chat_hint", "Chat: F6/Escape closes menu; T/Y open chat." },
            { "log_renderers", "Log renderers" },
            { "slot_loaded", " loaded." },
            { "slot_save_failed", "Could not save slot (check MelonLoader log)." },
            { "part_head", "Head" },
            { "part_spine", "Spine" },
            { "part_leg_l", "Leg L" },
            { "part_leg_r", "Leg R" },
            { "part_arm_l", "Arm L" },
            { "part_arm_r", "Arm R" },
            { "part_crown", "Crown" },
            { "part_wings", "Wings" }
        };

        private static readonly Dictionary<string, string> Spanish = new Dictionary<string, string>
        {
            { "tab_body", "Cuerpo" },
            { "tab_glow", "Glow" },
            { "glow_body_blend", "Mezcla color cuerpo" },
            { "body_gradients", "Gradientes por hueso" },
            { "half_color", "Color mitad inferior" },
            { "slot_add", "+ Añadir slot" },
            { "slot_rename", "Nombre" },
            { "tab_hats", "Sombreros" },
            { "tab_wingcust", "WINGCUST" },
            { "tab_shoes", "Zapatos" },
            { "wing_hint", "Alas del minijuego — solo estéticas. No inicia el minijuego de alas." },
            { "wing_enable", "Activar alas" },
            { "wing_on", "Alas activadas." },
            { "wing_off", "Alas desactivadas." },
            { "wing_pick", "Activa el toggle para ver alas en partida." },
            { "wing_scale", "Tamaño alas: " },
            { "wing_style", "Estilo: minijuego (look vanilla)" },
            { "wing_not_ready", "TODAVÍA NO ESTÁ FUNCIONAL 100%\nNO USAR" },
            { "wing_not_ready_hint", "Las alas están desactivadas en partida hasta el próximo arreglo. Sin coste de CPU mientras estén apagadas." },
            { "tab_weapons", "Armas" },
            { "tab_slots", "Slots" },
            { "tab_advanced", "Avanzado" },
            { "tab_settings", "Ajustes" },
            { "color_wheel", "Rueda cromática" },
            { "apply_now", "Aplicar ahora" },
            { "save", "Guardar" },
            { "load", "Cargar" },
            { "empty", "Vacío" },
            { "saved", "Guardado" },
            { "slot", "Slot" },
            { "style_presets", "Presets de estilo" },
            { "weapon_presets", "Presets de arma" },
            { "weapon_neon", "Neon (brillo)" },
            { "weapon_enable", "Activar color de arma" },
            { "body_enable", "Usar colores personalizados" },
            { "language", "Idioma del menú" },
            { "english", "Inglés" },
            { "spanish", "Español" },
            { "active", "Activo" },
            { "save_config", "Guardar config (archivo)" },
            { "sync_lobby", "Sincronizar lobby" },
            { "made_by_alka", "by alka · AlkaRealSkinChanger" },
            { "weapon_hint", "Solo arma equipada. Solo tú lo ves." },
            { "slots_hint", "Guarda hasta 3 estilos." },
            { "menu_hint_keys", "F6 o Escape cierra  |  T/Y cierran menú para abrir chat" },
            { "body_part", "Parte del cuerpo" },
            { "body_enable_hint", "Activa el toggle para editar y aplicar colores al cuerpo." },
            { "body_disabled", "Colores desactivados (sin coste por frame)." },
            { "body_enabled", "Colores personalizados activados." },
            { "repaint_body", "Repintar todo el cuerpo" },
            { "reset_part", "Reset parte" },
            { "part_reset", "Parte en blanco." },
            { "body_applied", "Cuerpo aplicado." },
            { "halves_enable", "Activar mitades por hueso" },
            { "halves_enable_hint", "Activa el toggle para gradientes en espina, brazos y piernas." },
            { "halves_need_body", "Activa colores personalizados en la pestaña Cuerpo." },
            { "halves_proximal", "proximal (hereda Cuerpo)" },
            { "halves_distal", "Distal (mitad inferior)" },
            { "halves_bone_cut", "Corte en hueso: " },
            { "halves_apply", "Aplicar mitades" },
            { "halves_applied", "Mitades recalculadas." },
            { "glow_color_label", "Color del aura (independiente del cuerpo)" },
            { "glow_enable", "Activar glow" },
            { "glow_on", "Glow activado." },
            { "glow_off", "Glow desactivado." },
            { "glow_updated", "Color del glow actualizado." },
            { "glow_strength", "Intensidad: " },
            { "glow_zones", "Zonas del prefab" },
            { "glow_width", "Ancho aura: " },
            { "glow_alpha", "Transparencia: " },
            { "glow_apply", "Aplicar glow" },
            { "glow_remove", "Quitar glow" },
            { "glow_applied", "Aura aplicada." },
            { "glow_removed", "Glow quitado." },
            { "zone_head", "Cabeza" },
            { "zone_torso", "Torso" },
            { "zone_arms", "Brazos" },
            { "zone_legs", "Piernas" },
            { "zone_wings", "Alas" },
            { "hat_hint", "Cosmético local + sync entre jugadores con el mod." },
            { "hat_enable", "Activar sombrero" },
            { "hat_on", "Sombrero activado." },
            { "hat_off", "Sombrero desactivado." },
            { "hat_pick", "Activa el toggle para elegir un sombrero." },
            { "hat_model", "Modelo" },
            { "hat_classic", "Clásicos" },
            { "hat_categories", "Categorías (10 c/u)" },
            { "hat_category_click_hint", "Clic en «10 OPCIONES» de cada fila para abrir el selector." },
            { "hat_variants_open", "10 OPCIONES ▶" },
            { "hat_variants_close", "◀ CERRAR" },
            { "hat_pick_variant", "elige una" },
            { "hat_close_panel", "Cerrar" },
            { "shoe_hint", "Solo estético. No afecta el gameplay." },
            { "shoe_enable", "Activar zapatos" },
            { "shoe_on", "Zapatos activados." },
            { "shoe_off", "Zapatos desactivados." },
            { "shoe_pick", "Activa el toggle para elegir zapatos." },
            { "shoe_model", "Modelo" },
            { "shoe_coming_soon", "PRÓXIMAMENTE" },
            { "shoe_coming_soon_hint", "Vista previa de zapatos — aún no se aplican en partida." },
            { "shoe_preview_label", "Vista previa (bloqueado)" },
            { "tab_tops", "Ropa" },
            { "tab_objects", "Objetos" },
            { "objects_hint", "Cosméticos orbitando o en la espalda que siguen al stickman." },
            { "objects_enable", "Activar objetos" },
            { "objects_on", "Objetos activados." },
            { "objects_off", "Objetos desactivados." },
            { "objects_pick", "Activa el interruptor para elegir un objeto." },
            { "objects_scale", "Escala" },
            { "tops_hint", "Prenda de arriba — vista lateral. Se adjunta al torso." },
            { "tops_enable", "Activar prenda" },
            { "tops_on", "Prenda activada." },
            { "tops_off", "Prenda desactivada." },
            { "tops_pick", "Activa el toggle para elegir una prenda." },
            { "tops_model", "Modelo" },
            { "weapon_color", "Color del arma" },
            { "weapon_on", "Color de arma activado." },
            { "weapon_off", "Color de arma desactivado." },
            { "weapon_pick", "Activa el toggle para teñir el arma equipada." },
            { "weapon_updated", "Color de arma actualizado." },
            { "weapon_tint_mesh", "Teñir modelo (mesh / líneas)" },
            { "weapon_tint_particles", "Teñir partículas (muzzle, etc.)" },
            { "weapon_repainted", "Arma activa repintada." },
            { "options", "Opciones" },
            { "menu_size", "Tamaño ventana menú" },
            { "menu_smaller", "Más pequeña −" },
            { "menu_larger", "Más grande +" },
            { "menu_reset_size", "Tamaño por defecto" },
            { "menu_size_hint", "Arrastra la esquina ◢ o usa los botones. Se guarda en config." },
            { "mp_safe", "MP compatible vanilla (recomendado: sin paquetes P2P extra)" },
            { "mp_safe_on", "Modo seguro: compatible vanilla; sync entre mods (Steam + ping)." },
            { "mod_sync_hint", "Quien tenga el mismo DLL ve tus colores en lobby/partida (Steam + Ping vanilla). Sombreros por lobby." },
            { "mp_safe_off", "Modo avanzado: sin restriccion extra de red." },
            { "uniform_skin", "Skin unificado (MP / estilo mod simple)" },
            { "rgb_anim", "RGB animado (solo cuerpo)" },
            { "glow_lobby", "Mantener glow en menú de lobby (off = más FPS)" },
            { "config_saved", "Config guardada en disco." },
            { "sync_sent", "Sync enviado." },
            { "skin_code", "Código de skin (compartir)" },
            { "gen_code", "Guardar código" },
            { "copy_code", "Copiar código" },
            { "paste_import", "Pegar código para importar" },
            { "import", "Importar" },
            { "paste", "Pegar" },
            { "code_copied", "Código copiado al portapapeles." },
            { "code_pasted", "Código pegado." },
            { "code_invalid", "Código inválido. Debe empezar con SFCCSKIN4|" },
            { "skin_imported", "Skin importada y aplicada." },
            { "code_fail", "No se pudo generar el código." },
            { "code_ok", "Código generado. Usa Copiar código." },
            { "mp_sync_hint", "Sync entre mods: sfcc en lobby + ping en partida. Vanilla: ignorados." },
            { "chat_hint", "Chat: F6/Escape cierra menú; T/Y abren chat." },
            { "log_renderers", "Log renderers" },
            { "slot_loaded", " cargado." },
            { "slot_save_failed", "No se pudo guardar el slot (mirá el log de MelonLoader)." },
            { "part_head", "Cabeza" },
            { "part_spine", "Espina" },
            { "part_leg_l", "Pierna L" },
            { "part_leg_r", "Pierna R" },
            { "part_arm_l", "Brazo L" },
            { "part_arm_r", "Brazo R" },
            { "part_crown", "Corona" },
            { "part_wings", "Alas" }
        };

        public static void SetLanguage(MenuLanguage lang)
        {
            if (ColorCustomizerApp.Instance != null && ColorCustomizerApp.Instance.Config != null)
            {
                ColorCustomizerApp.Instance.Config.MenuLanguage = lang;
                ColorConfigStore.Save(ColorCustomizerApp.Instance.Config);
            }
        }

        public static string T(string key)
        {
            MenuLanguage lang = MenuLanguage.English;
            if (ColorCustomizerApp.Instance != null && ColorCustomizerApp.Instance.Config != null)
            {
                lang = ColorCustomizerApp.Instance.Config.MenuLanguage;
            }

            Dictionary<string, string> table = lang == MenuLanguage.Spanish ? Spanish : English;
            string value;
            if (table.TryGetValue(key, out value))
            {
                return value;
            }

            return key;
        }

        public static string[] GetTabLabels()
        {
            return new[]
            {
                T("tab_body"),
                T("tab_glow"),
                T("tab_hats"),
                T("tab_wingcust"),
                T("tab_shoes"),
                T("tab_tops"),
                T("tab_objects"),
                T("tab_weapons"),
                T("tab_slots"),
                T("tab_advanced"),
                T("tab_settings")
            };
        }

        public static string[] GetPartLabels()
        {
            return new[]
            {
                T("part_head"),
                T("part_spine"),
                T("part_leg_l"),
                T("part_leg_r"),
                T("part_arm_l"),
                T("part_arm_r"),
                T("part_crown"),
                T("part_wings")
            };
        }
    }
}
